credit_card_dwh:
  outputs:
    dev:
      dataset: final_project
      fixed_retries: 1
      keyfile: service-account.json
      location: us
      method: service-account
      priority: interactive
      project: "data-fellowship-9-project"
      threads: 4
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: final_project
      fixed_retries: 1
      keyfile: service-account.json
      location: us
      method: service-account
      priority: interactive
      project: "data-fellowship-9-project"
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
